<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exception handling</title>
    <link rel="stylesheet" href="../../../../public/style.css">
    <link rel="icon" href="../../../../public/logo/favicon_io/favicon.ico">
    <link rel="stylesheet" id="highlightStylesheet"
        href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/tomorrow-night-blue.min.css">
</head>

<body class="bg-c">
    <div id="mySidepanel" class="sidepanel">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">Ã—</a>
        <a href="../index.html" class="home">back</a>
        <div class="botbut">
            <a href="./stl.html" class="link">Next Topic &rarr;</a>
            <a href="./file.html" class="link">&larr; Previous Topic</a>
        </div>
    </div>
    <div id="navbar" class="grad">
        <div>
            <div class="openbtn" onclick="openNav()">
                <div id="nav-icon1" for="nav-menu1">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
        <div>
            <h2>Exception handling</h2>
        </div>
    </div>
    <div class="content-box">
        <h1>Exception handling</h1>
        <ul>
            <li>Exception are type of error</li>

            <li>Let's quickly brush up the concept of error.</li>
            <li>Errors are the mistake made by the programmer.</li>
            <li>Error are of two type:
                <ul>
                    <li>Syntactic error: example - missing of semicolon, colon, brackets, etc. Basically where we are
                        using wrong syntax.
                    </li>
                    <li>Logical error: example - using wrong formula for calculation.</li>
                </ul>
            </li>
            <li>Now all those error which are run time error like dividing by zero, accessing value at wrong index of
                array comes under exception.</li>
        </ul>
        <p>Now let's discuss exception handling &darr;</p>
        <ul>
            <li>Exception handling is a much elegant solution as compared to other error handling mechanisms (handling
                through if-else blocks).
                <ul>
                    <li>It enables separation of main logic and error handling code. </li>
                </ul>
            </li>
            <li>Exception handling provide a systematic, object-oriented approach to handling erros generated by C++
                classes.
                <br>For example:
                <ul>
                    <li>running out of memory</li>
                    <li>not being able to open a file</li>
                    <li>or using out-of-bound index</li>
                </ul>
            </li>
        </ul>
        <div class="wh">
            <h2>Exception handling process</h2>
            <ul>
                <li>Programmer writes the code that is suspected to cause an exception in <b>try block</b>.</li>
                <li>Code section that encounters an error <b>throws</b> an object that is used to represent exception.
                </li>
                <li><b>Catch block</b> follow try block to catch the object thrown. </li>
            </ul>
            <div class="in">
                <h3>Syntax - Throw</h3>
                <ul>
                    <li>The keyword <b>throw</b> is used to throw an exception.</li>
                    <li>Any expression can be used to represent the exception that has occured</li>
                </ul>
                <pre>
                    <code>
throw n;
throw (n);    
                    </code>
                </pre>
            </div>
            <div class="in">
                <h3>Syntax - Try and Catch</h3>
                <pre>
                    <code>
int main()
{
    try{
        ... 
    }
    catch(Exception1 obj)
    {
        ...
    }
    catch(Exception2 obj)
    {
        ...
    }
    return 0;
}
                    </code>
                </pre>
            </div>
            <div class="in">
                <h3>Catch blocks</h3>
                <ul>
                    <li>Catch handler must be preceded by a <b>try block</b> or any other <b>catch handler</b>. </li>
                    <li><b>Catch handlers</b> are only executed when an exception has occured.</li>
                    <li>The catch blocks are tried in order they are written.</li>
                </ul>
            </div>
            <p>Let's understand with program</p>
            <ul>
                <li>Program which divide two number:
                    <ul>
                        <li>We know that if divisor is zero, this will cause exception.</li>
                    </ul>
                </li>
                <li>First we will see program without using exceptional handling &darr;</li>
            </ul>
            <div class='code'>
                <div class='dotc'></div>
                <pre>
                   <code>
#include &lt;iostream>
using namespace std;

int main()
{
    int a, b, r;
    cout << "Enter the value of a : ";
    cin >> a;
    cout << "Enter the value of b : ";
    cin >> b;
    if (b != 0)
        r = a / b;
    else
    {
        cout << "Cannot divide by zero";
    }

    return 0;
}
                   </code>
               </pre>
            </div>
            <p>Output &darr;</p>
            <pre>
                <code>
Enter the value of a : 12
Enter the value of b : 0
Cannot divide by zero
                </code>
            </pre>
            <p>Now we will implement it using try and catch block</p>
            <div class='code'>
                <div class='dotc'></div>
                <pre>
                   <code>
#include &lt;iostream>
using namespace std;

int main()
{
    int a, b;
    float r;
    cout << "Enter the value of a : ";
    cin >> a;
    try
    {
        cout << "Enter the value of b : ";
        cin >> b;
        if (b == 0)
            throw 0;
        r = a / b;
        cout << "The result if : " << r << endl;
    }
    catch (int)
    {
        cout << "cannot divide by zero" << endl;
    }
    return 0;
}
                   </code>
                </pre>
                <p>Output &darr;</p>
                <pre>
                <code>
Enter the value of a : 14
Enter the value of b : 0
cannot divide by zero
                </code>
               </pre>
                <pre>
                <code>
Enter the value of a : 15
Enter the value of b : 3
The result is : 5
                </code>
               </pre>
            </div>
        </div>
        <div class="content-box">
            <p>Reference &darr;</p>
            <ul>
                <li><a href="https://www.youtube.com/watch?v=zHAVXDA_iNI" target="_blank">
                        (youtube vid) &neArr; </a></li>
                <li><a href="https://www.youtube.com/watch?v=vOXOzGjmwTw" target="_blank">
                        (youtube vid) &neArr; </a></li>
            </ul>
        </div>
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
        <script src="../../../../public/main.js"></script>
</body>

</html>